Project Akhir/Project/Intelligence_creation/Project_Intelligence_Creation/Project_Intelligence_Creation/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('input_data.urls','input_data'),namespace='input_data')),
]

Project Akhir/Project/Intelligence_creation/Project_Intelligence_Creation/input_data/urls.py
from django.urls import path
from . import views
from django.conf.urls.static import static
from django.conf import settings

app_name = 'input_data' 

urlpatterns = [

    path('projects/', views.ProjectListCreateAPIView.as_view(), name='project_list_create'),
    path('projects/<int:pk>/', views.ProjectRetrieveUpdateDestroyAPIView.as_view(), name='project_detail'),

    path('', views.project_list, name='project_list'),
    path('projectss/create/', views.project_create, name='project_create'),
    path('projectss/<int:pk>/update/', views.project_update, name='project_update'),
    path('projectss/<int:pk>/delete/', views.project_delete, name='project_delete'),
    path('projectss/<int:pk>/', views.project_detail, name='project_detail'),

    path('datasets/', views.dataset_list, name='dataset_list'),
    path('datasets/new/', views.dataset_create, name='dataset_create'),
    path('datasets/<int:pk>/edit/', views.dataset_update, name='dataset_update'),
    path('datasets/<int:pk>/delete/', views.dataset_delete, name='dataset_delete'),
    path('datasets/<int:pk>/', views.dataset_detail, name='dataset_detail'),
    path('<int:pk>/add_column/', views.add_column, name='add_column'),
    path('edit_column/<int:pk>/', views.edit_column, name='edit_column'),
    path('delete_column/<int:pk>/', views.delete_column, name='delete_column'),

    path('proses/', views.proses_list, name='proses_list'),
    path('proses/create/', views.proses_create, name='proses_create'),
    path('proses/<int:pk>/update/', views.proses_update, name='proses_update'),
    path('proses/<int:pk>/delete/', views.proses_delete, name='proses_delete'),
    path('proses/<int:pk>/', views.proses_detail, name='proses_detail'),
    path('proses/<int:pk>/status/<str:status>/', views.proses_status_update, name='proses_status_update'),

    path('model-planning/', views.model_planning_list, name='model_planning_list'),
    path('model-planning/new/', views.model_planning_create, name='model_planning_create'),
    path('model-planning/<int:pk>/', views.model_planning_detail, name='model_planning_detail'),
    path('model-planning/<int:pk>/edit/', views.model_planning_update, name='model_planning_update'),
    path('model-planning/<int:pk>/delete/', views.model_planning_delete, name='model_planning_delete'),

    path('refining-planning/', views.refining_planning_list, name='refining_planning_list'),
    path('refining-planning/new/', views.refining_planning_create, name='refining_planning_create'),
    path('refining-planning/<int:pk>/', views.refining_planning_detail, name='refining_planning_detail'),
    path('refining-planning/<int:pk>/edit/', views.refining_planning_update, name='refining_planning_update'),
    path('refining-planning/<int:pk>/delete/', views.refining_planning_delete, name='refining_planning_delete'),

    path('training-testing-result/', views.training_testing_result_list, name='training_testing_result_list'),
    path('training-testing-result/new/', views.training_testing_result_create, name='training_testing_result_create'),
    path('training-testing-result/<int:pk>/', views.training_testing_result_detail, name='training_testing_result_detail'),
    path('training-testing-result/<int:pk>/edit/', views.training_testing_result_update, name='training_testing_result_update'),
    path('training-testing-result/<int:pk>/delete/', views.training_testing_result_delete, name='training_testing_result_delete'),

    path('refining-results/', views.refining_result_list, name='refining_result_list'),
    path('refining-results/new/', views.refining_result_create, name='refining_result_create'),
    path('refining-results/<int:pk>/', views.refining_result_detail, name='refining_result_detail'),
    path('refining-results/<int:pk>/edit/', views.refining_result_update, name='refining_result_update'),
    path('refining-results/<int:pk>/delete/', views.refining_result_delete, name='refining_result_delete'),

    path('komunikasi_manajemen/', views.komunikasi_manajemen_list,name='komunikasi_manajemen_list'),
    path('komunikasi_manajemen/create/', views.komunikasi_manajemen_create,name='komunikasi_manajemen_create'),
    path('komunikasi_manajemen/<int:pk>/', views.komunikasi_manajemen_detail, name='komunikasi_manajemen_detail'),
    path('komunikasi_manajemen/update/<int:pk>/update/', views.komunikasi_manajemen_update, name='komunikasi_manajemen_update'),
    path('komunikasi_manajemen/delete/<int:pk>/delete/', views.komunikasi_manajemen_delete, name='komunikasi_manajemen_delete'),

    path('datasetss/', views.DatasetListCreateAPIView.as_view(), name='dataset-list-create'),
    path('datasetss/<int:pk>/', views.DatasetRetrieveUpdateDestroyAPIView.as_view(), name='dataset-retrieve-update-destroy'),
    path('columnss/', views.ColumnListCreateAPIView.as_view(), name='column-list-create'),
    path('columnss/<int:pk>/', views.ColumnRetrieveUpdateDestroyAPIView.as_view(), name='column-retrieve-update-destroy'),

    path('view/', views.file_list, name='file_list'),
    path('apiprojects/', views.apiproject_list, name='apiproject_list'),

    path('training-testing-results/', views.TrainingTestingResultList.as_view(), name='training-testing-result-list'),
    path('training-testing-results/<int:pk>/', views.TrainingTestingResultDetail.as_view(), name='training-testing-result-detail'),
    path('komunikasi-manajemen/', views.KomunikasiManajemenListCreate.as_view(), name='komunikasi-manajemen-list-create'),
    path('komunikasi-manajemen/<int:pk>/', views.KomunikasiManajemenDetail.as_view(), name='komunikasi-manajemen-detail'), 
     path('fetch_data/', views.fetch_api_data, name='fetch_data'),
    path('update_status/', views.update_status, name='update_status'),
    path('status-form/', views.status_form_view, name='status-form'),
    path('project-info/', views.project_view, name='project-info'),
    ]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Project Akhir/Project/Intelligence_creation/Project_Intelligence_Creation/input_data/models.py
from django.db import models
from django.core.validators import FileExtensionValidator

class DataProjek(models.Model):
    
    nama_proyek = models.CharField(max_length=200, null=False)

    def __str__(self):
        return self.nama_proyek


class Pekerjaan(models.Model):
    status = models.CharField(max_length=100)
    def __str__(self):
        return self.status

class Project(models.Model):
    project_id = models.CharField(max_length=100, null=True, blank=True)
    project_name = models.CharField(max_length=100, null=True, blank=True)
    description = models.TextField(max_length=250, null=True, blank=True)
    algorithm = models.CharField(max_length=50, null=True, blank=True)
    output = models.TextField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.project_name

class Dataset(models.Model):
    name = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='datasets')
    nama_dataset = models.CharField(max_length=100, null=True, blank=True)
    description = models.TextField()

    def __str__(self):
        return self.nama_dataset or "Unnamed Dataset"

class Column(models.Model):
    dataset = models.ForeignKey(Dataset, related_name='columns', on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    data_type = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class Proses(models.Model):
    nama_aktivitas = models.Field()
    deskripsi_aktivitas = models.TextField()
    dataset_yang_dipakai = models.ForeignKey('Dataset', on_delete=models.CASCADE)
    result_file = models.FileField(upload_to='activity_results/')

    STATUS_CHOICES = [
        ('Belum Selesai', 'Belum Selesai'),
        ('Sedang Proses', 'Sedang Proses'),
        ('Selesai', 'Selesai'),
    ]
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='Belum Selesai')

    def __str__(self):
        return self.nama_aktivitas

class ModelPlanning(models.Model):
    model_name = models.CharField(max_length=100)
    deskripsi_model = models.TextField(max_length=100, null=True, blank=True)
    tujuan_model = models.TextField(max_length=100, null=True, blank=True)
    nama_algoritma = models.CharField(max_length=100, null=True, blank=True)
    kebutuhan_data = models.TextField(max_length=100, null=True, blank=True)
    metodologi_pengujian = models.TextField(max_length=100, null=True, blank=True)
    metode_pengukuran = models.TextField(max_length=100, null=True, blank=True)

    def __str__(self):
        return self.model_name

class RefiningPlanning(models.Model):
    model_name = models.ForeignKey(ModelPlanning, on_delete=models.CASCADE, related_name='refinings')
    description = models.TextField()
    refining_goal = models.TextField()
    refining_strategy = models.CharField(max_length=100)
    additional_data = models.TextField()
    evaluation_methodology = models.TextField()
    measurement_method = models.TextField()
    evaluasi_model_awal = models.TextField(max_length=100, null=True, blank=True)

    def __str__(self):
        return str(self.model_name)

class TrainingTestingResult(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    dataset = models.ForeignKey(Dataset, on_delete=models.CASCADE)
    activity = models.ForeignKey(ModelPlanning, on_delete=models.CASCADE)
    training_result = models.FileField(upload_to='training_results/')
    testing_result = models.FileField(upload_to='testing_results/')
      

class RefiningResult(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    dataset = models.ForeignKey(Dataset, on_delete=models.CASCADE)
    activity = models.ForeignKey(ModelPlanning, on_delete=models.CASCADE)
    refining_result = models.FileField(upload_to='refining_results/')
class KomunikasiManajemen(models.Model):
    status = models.TextField(max_length=250, null=True, blank=True)

    def __str__(self):
        return self.status if self.status else "No Status"

Project Akhir/Project/Intelligence_creation/Project_Intelligence_Creation/input_data/forms.py
# forms.py
from django import forms
from .models import Project,Dataset, Column
from django.forms import inlineformset_factory
from .models import Proses
from .models import ModelPlanning
from .models import RefiningPlanning
from .models import TrainingTestingResult
from .models import RefiningResult

from .models import KomunikasiManajemen


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['project_id', 'project_name', 'description', 'algorithm', 'output']

class DatasetForm(forms.ModelForm):
    class Meta:
        model = Dataset
        fields = ['name', 'description', 'nama_dataset']

class ColumnForm(forms.ModelForm):
    class Meta:

        model = Column
        fields = ['name', 'data_type']

ColumnFormSet = inlineformset_factory(Dataset, Column, form=ColumnForm, extra=1, can_delete=True)



class ProsesForm(forms.ModelForm):
    class Meta:
        model = Proses
        fields = ['nama_aktivitas', 'deskripsi_aktivitas', 'dataset_yang_dipakai', 'result_file', 'status']  

    def __init__(self, *args, **kwargs):
        super(ProsesForm, self).__init__(*args, **kwargs)
        self.fields['status'].choices = [('Selesai', 'Selesai'), ('Sedang Proses', 'Sedang Proses'), ('Belum Selesai', 'Belum Selesai')]
        self.fields['result_file'].widget.attrs['accept'] = '.csv, application/vnd.ms-excel, application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'

class ModelPlanningForm(forms.ModelForm):
    class Meta:
          
        model = ModelPlanning 
        fields = [
            'model_name',
            'deskripsi_model',
            'tujuan_model',
            'nama_algoritma',
            'kebutuhan_data',
            'metodologi_pengujian',
            'metode_pengukuran',
        ]



class RefiningPlanningForm(forms.ModelForm):
    class Meta:
        model = RefiningPlanning
        fields = [
            'model_name',
            'description',
            'refining_goal',
            'refining_strategy',
            'additional_data',
            'evaluation_methodology',
            'measurement_method',
            'evaluasi_model_awal',
        ]



class TrainingTestingResultForm(forms.ModelForm):
    class Meta:
        model = TrainingTestingResult
        fields = ['project', 'dataset', 'activity', 'training_result', 'testing_result']

class RefiningResultForm(forms.ModelForm):
    class Meta:
        model = RefiningResult
        fields = ['project', 'dataset', 'activity', 'refining_result']


class KomunikasiManajemenForm(forms.ModelForm):
    class Meta:
        model = KomunikasiManajemen
        fields = ['status']

Project Akhir/Project/Intelligence_creation/Project_Intelligence_Creation/input_data/templates/input_data/dataset_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Daftar Dataset{% endblock %}

{% block content %}
    <div class="container">
        <!-- Bagian Daftar Dataset -->
        <div id="dataset-section" class="content-section active-section">
            <div class="alert alert-warning" role="alert">
                Daftar Dataset
            </div>
            
            <form>
                <a href="{% url 'input_data:dataset_create' %}" class="btn btn-success ml-2">Create</a>
                <a href="{% url 'input_data:file_list' %}?dataset_id={{ dataset.pk }}" class="btn btn-primary m1-2">Lihat File</a>
            </form>
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Nama Dataset</th>
                        <th scope="col">Aksi</th>
                    </tr>
                </thead>
                <tbody>
                    {% for dataset in datasets %}
                        <tr>
                            <td><a href="{% url 'input_data:dataset_detail' dataset.pk %}">{{ dataset.name }}</a></td>
                            <td>
                                <a href="{% url 'input_data:dataset_update' dataset.pk %}" class="btn btn-outline-success btn-sm">Edit</a>
                                <form method="post" action="{% url 'input_data:dataset_delete' dataset.pk %}" style="display:inline;" onsubmit="return confirmDelete();">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-outline-danger">Delete</button>
                                </form>
                                <a href="{% url 'input_data:dataset_detail' dataset.pk %}" class="btn btn-outline-primary btn-sm">View</a>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="2">No datasets found</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <script>
        function confirmDelete() {
            return confirm("Are you sure you want to delete this project?");
        }
    </script>
{% endblock %}

Project Akhir/Project/Intelligence_creation/Project_Intelligence_Creation/input_data/templates/input_data/edit_column.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% if column_form.instance.pk %}Update{% else %}Edit{% endif %} Column</title>
    <link rel="stylesheet" href="{% static 'Intelligence_creation/style.css' %}">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <h1>{% if column_form.instance.pk %}Update{% else %}Edit{% endif %} Column</h1>
        <form method="post">
            {% csrf_token %}
            <div class="form-group">
                <label for="id_name">Column Name:</label>
                <input type="text" id="id_name" name="name" class="form-control" value="{{ column_form.instance.name }}">
            </div>
            <div class="form-group">
                <label for="id_data_type">Data Type:</label>
                <input type="text" id="id_data_type" name="data_type" class="form-control" value="{{ column_form.instance.data_type }}">
            </div>
            <button type="submit" class="btn btn-primary">{% if column_form.instance.pk %}Update{% else %}Edit{% endif %} Column</button>
        </form>
        <a href="{% url 'input_data:add_column' column.dataset.pk %}" class="btn btn-secondary">Back to Columns</a>
    </div>
</body>
</html>

Project Akhir/Project/Intelligence_creation/Project_Intelligence_Creation/input_data/templates/input_data/komunikasi_manajemen_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% if form.instance.pk %}Update{% else %}Create{% endif %} Komunikasi Manajemen</title>
    <link rel="stylesheet" type="text/css" href="{% static 'Intelligence_creation/style.css' %}">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>{% if form.instance.pk %}Update{% else %}Create{% endif %} Komunikasi Manajemen</h1>
        </div>
        <div class="content">
            <form method="POST" enctype="multipart/form-data" action="{% if form.instance.pk %}{% url 'input_data:komunikasi_manajemen_update' form.instance.pk %}{% else %}{% url 'input_data:komunikasi_manajemen_create' %}{% endif %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_nama_proyek">Status:</label>
                    {{ form.status }}
                </div>
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a href="{% url 'input_data:komunikasi_manajemen_list' %}" class="btn btn-secondary">Back to List</a>
                </div>
            </form>
        </div>
    </div>
</body>
</html>

Project Akhir/Project/Intelligence_creation/Project_Intelligence_Creation/input_data/templates/input_data/model_planning_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Form Perencanaan Model</title>
    <link rel="stylesheet" href="{% static 'Intelligence_creation/style.css' %}">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">  
</head>
<style>
       
    body {
        background-color: #80b5b2;
        padding: 20px;
    }
    .container {
        background-color: #fff;
        padding: 30px;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        max-width: 600px; /* Optional: Adjust container width */

    }
</style>
<body>
    <div class="container">
        <h2 class="mb-4">Form Perencanaan Model</h2>
        <form id="model-planning-form" method="POST">
            {% csrf_token %}
            <!-- Nama Model -->
            <div class="form-group">
                <label for="id_model_name">Nama Model:</label>
                {{ form.model_name }}
            </div>
            
            <!-- Evaluasi Awal -->
            <div class="form-group">
                <label for="id_initial_evaluation">Deskripsi Model:</label>
                {{ form.deskripsi_model }}
            </div>
            
            <!-- Identifikasi Masalah -->
            <div class="form-group">
                <label for="id_problem_identification">Tujuan Model:</label>
                {{ form.tujuan_model }}
            </div>
            
            <!-- Strategi Refining -->
            <div class="form-group">
                <label for="id_refining_strategy">Nama Algoritma:</label>
                {{ form.nama_algoritma }}
            </div>
            
            <!-- Data Tambahan -->
            <div class="form-group">
                <label for="id_additional_data">Kebutuhan Data:</label>
                {{ form.kebutuhan_data }}
            </div>
            
            <!-- Metodologi Pengujian Refining -->
            <div class="form-group">
                <label for="id_evaluation_methodology">Metodologi Pengujian :</label>
                {{ form.metodologi_pengujian }}
            </div>
            
            <!-- Tujuan Refining -->
            <div class="form-group">
                <label for="id_refining_goal">Metode Pengukuran:</label>
                {{ form.metode_pengukuran }}
            </div>        
            <!-- Tombol Submit dan Kembali -->
            <div class="form-group">
                <a href="{% url 'input_data:model_planning_list' %}" class="btn btn-outline-secondary">Back to List</a>
                
                <button type="submit" class="btn btn-primary">Simpan</button>
                <a href="{% url 'input_data:model_planning_list' %}" class="btn btn-secondary">Kembali ke Daftar</a>
            </div>
        </form>
    </div>
</body>
</html>

Project Akhir/Project/Intelligence_creation/Project_Intelligence_Creation/input_data/templates/input_data/proses_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% if form.instance.pk %}Update{% else %}Create{% endif %} Proses</title>
    <link rel="stylesheet" type="text/css" href="{% static 'Intelligence_creation/style.css' %}">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<div class="container">
    <div class="header">
        <h1>{% if form.instance.pk %}Update{% else %}Create{% endif %} Proses</h1>
    </div>
    <div class="content">
        <form method="POST" enctype="multipart/form-data" action="{% if form.instance.pk %}{% url 'input_data:proses_update' form.instance.pk %}{% else %}{% url 'input_data:proses_create' %}{% endif %}">
            {% csrf_token %}
            
            <div class="form-group">
                <label for="id_nama_proses">Nama Proses:</label>
                {{ form.nama_aktivitas }}
                {% if form.nama_aktivitas.errors %}
                    <div class="invalid-feedback d-block">{{ form.nama_aktivitas.errors }}</div>
                {% endif %}
            </div>
            
            <div class="form-group">
                <label for="id_deskripsi_proses">Deskripsi Proses:</label>
                {{ form.deskripsi_aktivitas }}
                {% if form.deskripsi_aktivitas.errors %}
                    <div class="invalid-feedback d-block">{{ form.deskripsi_aktivitas.errors }}</div>
                {% endif %}
            </div>
            
            <div class="form-group">
                <label for="id_dataset_yang_dipakai">Dataset Yang Dipakai:</label>
                {{ form.dataset_yang_dipakai }}
                {% if form.dataset_yang_dipakai.errors %}
                    <div class="invalid-feedback d-block">{{ form.dataset_yang_dipakai.errors }}</div>
                {% endif %}
            </div>
            
            <div class="form-group">
                <label for="id_result_file">Upload File Hasil:</label>
                {{ form.result_file }}
                {% if form.result_file.errors %}
                    <div class="invalid-feedback d-block">{{ form.result_file.errors }}</div>
                {% endif %}
            </div>
            
            <div class="form-group">
                <label for="id_status">Status:</label>
                {{ form.status }}
                {% if form.status.errors %}
                    <div class="invalid-feedback d-block">{{ form.status.errors }}</div>
                {% endif %}
            </div>
            
            <button type="submit" class="btn btn-primary">Save</button>
        </form>
    </div>
</div>
</body>
</html>

Project Akhir/Project/Intelligence_creation/Project_Intelligence_Creation/input_data/templates/input_data/refining_planning_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% if form.instance.pk %}Update{% else %}Create{% endif %} Refining Planning</title>
    <link rel="stylesheet" href="{% static 'Intelligence_creation/style.css' %}">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>{% if form.instance.pk %}Update{% else %}Create{% endif %} Refining Planning</h1>
        </div>
        <div class="content">
            <form id="refining-planning-form" method="POST" action="{% if form.instance.pk %}{% url 'input_data:refining_planning_update' pk=form.instance.pk %}{% else %}{% url 'input_data:refining_planning_create' %}{% endif %}">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_model_name">Nama Model:</label>
                    {{ form.model_name }}
                </div>
                <div class="form-group">
                    <label for="id_description">Identifikasi Masalah:</label>
                    {{ form.description }}
                </div>
                <div class="form-group">
                    <label for="id_refining_goal">Evaluasi Model Awal:</label>
                    {{ form.evaluasi_model_awal }}
                </div>
                <div class="form-group">
                    <label for="id_refining_goal">Tujuan Refining:</label>
                    {{ form.refining_goal }}
                </div>
                <div class="form-group">
                    <label for="id_algorithm">Strategi:</label>
                    {{ form.refining_strategy }}
                </div>
                <div class="form-group">
                    <label for="id_data_requirements">Kebutuhan Data:</label>
                    {{ form.additional_data }}
                </div>
                <div class="form-group">
                    <label for="id_evaluation_methodology">Metodologi Pengujian:</label>
                    {{ form.evaluation_methodology }}
                </div>

                <div class="form-group">
                    <label for="id_evaluation_methodology">Metodologi Pengukuran:</label>
                    {{ form.measurement_method}}
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Save</button>
                    <a href="{% url 'input_data:refining_planning_list' %}" class="btn btn-secondary">Back to List</a>
                </div>
            </form>
        </div>
    </div>
</body>
</html>

Project Akhir/Project/Intelligence_creation/Project_Intelligence_Creation/input_data/templates/input_data/refining_planning_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Refining Planning{% endblock %}
{% block content %}
    <div class="container">
        <!-- Bagian Daftar Perencanaan Refining -->
        <div id="refining-planning-section" class="content-section active-section">
            <div class="alert alert-warning" role="alert">
                Daftar Perencanaan Refining
            </div>
            <form>
                <a href="{% url 'input_data:refining_planning_create' %}" class="btn btn-success ml-2">Create</a>
            </form>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col">Nama Model</th>
                        <th scope="col">Aksi</th>
                    </tr>
                </thead>
                <tbody>
                    {% for plan in plans %}
                    <tr>
                        <td>{{ plan.model_name }}</td>
                        <td>
                            <a href="{% url 'input_data:refining_planning_update' pk=plan.pk %}" class="btn btn-outline-success">Edit</a>

                            <form method="post" action="{% url 'input_data:refining_planning_delete' plan.pk %}" style="display:inline;" onsubmit="return confirmDelete();">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">Delete</button>
                            </form>
                            <a href="{% url 'input_data:refining_planning_detail' pk=plan.pk %}" class="btn btn-outline-primary">Lihat</a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="2">Tidak ada perencanaan refining yang ditemukan.</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <script>
        function confirmDelete() {
            return confirm("Are you sure you want to delete this project?");
        }
    </script>
    {% endblock %}

Project Akhir/Project/Intelligence_creation/Project_Intelligence_Creation/input_data/templates/input_data/training_testing_result_list.html
{% extends "base.html" %}
{% load static %}

{% block title %}Training Result{% endblock %}
{% block content %}
    <div class="container">
        <!-- Bagian Daftar Hasil Pelatihan dan Pengujian -->
        <div id="training-testing-result-section" class="content-section active-section">
            <div class="alert alert-warning" role="alert">
                Daftar Hasil Pelatihan dan Pengujian
            </div>
            <form>
                <a href="{% url 'input_data:training_testing_result_create' %}" class="btn btn-success ml-2">Create</a>
            </form>
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th scope="col">Nama Proyek</th>
                        <th scope="col">Aksi</th>
                    </tr>
                </thead>
                <tbody>
                    {% for result in results %}
                        <tr class="record">
                            <td>{{ result.project }}</td>
                            <td>
                                <a href="{% url 'input_data:training_testing_result_update' result.pk %}" class="btn btn-outline-success">Edit</a>
                                <form method="post" action="{% url 'input_data:training_testing_result_delete' result.pk %}" style="display:inline;" onsubmit="return confirmDelete();">
                                    {% csrf_token %}
                                    <button type="submit" class="btn btn-danger">Delete</button>
                                </form>
                                <a href="{% url 'input_data:training_testing_result_detail' result.pk %}" class="btn btn-outline-primary">View</a>
                            </td>
                        </tr>
                    {% empty %}
                        <tr>
                            <td colspan="4">No results found</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    <script>
        function confirmDelete() {
            return confirm("Are you sure you want to delete this project?");
        }
    </script>
{% endblock %}